CREATE TABLE `verificentros`.`verificaciones`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `Creacion` TIMESTAMP NOT NULL,
    `Clave` TEXT NOT NULL,
    `Estatus` TEXT NOT NULL,
    `Folio` INT NOT NULL,
    `Fecha` DATE NOT NULL,
    `Hora` TIME NOT NULL,
    `Tecnico` TEXT NOT NULL,
    `Propietario` TEXT NOT NULL,
    `Domicilio` TEXT NOT NULL,
    `CodigoPostal` INT NOT NULL,
    `Municipio` TEXT NOT NULL,
    `Estado` TEXT NOT NULL,
    `ProximaVerificacion` TEXT NOT NULL,
    `Marca` TEXT NOT NULL,
    `Submarca` TEXT NOT NULL,
    `Modelo` INT NOT NULL,
    `Vin` TEXT NOT NULL,
    `Placa` TEXT NOT NULL,
    `Cilindros` INT NOT NULL,
    `HcCrucero` INT NOT NULL,
    `HcRealenti` INT NOT NULL,
    `CoCrucero` DOUBLE NOT NULL,
    `CoRealenti` DOUBLE NOT NULL,
    `O2Crucero` DOUBLE NOT NULL,
    `O2Realenti` DOUBLE NOT NULL,
    `CoCo2MinCrucero` DOUBLE NOT NULL,
    `CoCo2MinRealenti` DOUBLE NOT NULL,
    `CoCo2MaxCrucero` DOUBLE NOT NULL,
    `CoCo2MaxRealenti` DOUBLE NOT NULL,
    `FactorLambdaCrucero` DOUBLE NOT NULL,
    `FactorLambdaRealenti` DOUBLE NOT NULL,
    PRIMARY KEY(`id`)
) ENGINE = InnoDB;

CREATE TABLE `verificentros`.`users`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `User` TEXT NOT NULL,
    `Password` TEXT NOT NULL,
    `Clave` TEXT NOT NULL,
    `AccessLevel` TEXT NOT NULL,
    `Estatus` INT NOT NULL,
    PRIMARY KEY(`id`)
) ENGINE = InnoDB;
